# This is a basic workflow to help you get started with Actions

name: deno_mod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
    # Install Ubuntu OS updates
    #- name: Install OS updates, security fixes etc
    #  run: |
        #echo "Installing OS updates, security fixes etc"
        #sudo apt update
        #sudo apt -y upgrade
        #sudo apt -y autoremove
    
    # Install dependencies and Deno runtime
    # deno_uri="https://github.com/denoland/deno/releases/latest/download/deno-${target}.zip"
    # Linux (Ubuntu) target: deno-x86_64-unknown-linux-gnu.zip
    - name: Install dependencies and Deno runtime
      run: |
        echo "Installing Deno Ubuntu dependencies..."
        sudo apt -y install unzip git curl
        echo "Installing Deno runtime..."
        echo "Creating '$HOME/.deno/bin' directory.."
        mkdir -p $HOME/.deno/bin
        cd $HOME/.deno/bin
        curl -L https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -o deno.zip
        unzip ./deno.zip
        echo ""
        echo "Current directory and its contents are:"
        pwd
        ls -l
        echo ""
        echo "Installed version of Deno is:"
        $HOME/.deno/bin/deno --version
        echo ""
        echo "Installation environment for Deno is:"
        $HOME/.deno/bin/deno info
        echo ""
        echo "DONE INSTALL."

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs any Deno tests first
    - name: Run Deno tests
      run: |
        echo "Run the Deno application"
        PATH="${PATH}":$HOME/.deno/bin
        echo ""
        echo "Current directory and its contents are:"
        pwd
        ls -l
        echo ""
        echo "Execute tests:"
        echo ""
        deno test --allow-read
        echo ""
        echo "DONE."

    # Saves built file as a release.
    #- name: Upload artifact
    #  uses: actions/upload-artifact@main
    #  with:
    #    name: release
    #    path: bin